// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingbarController from "./bookingbar_controller"
application.register("bookingbar", BookingbarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
